# Generated by Django 4.1.4 on 2023-01-18 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0006_remove_gameplayer_game_remove_gameplayer_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayer',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='player',
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='game',
            field=models.ManyToManyField(to='games.game'),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='player',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
