# Generated by Django 4.1.4 on 2023-03-22 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0009_rename_testuju_playergame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Čas ukončení'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='game',
            field=models.ManyToManyField(blank=True, to='games.game'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='player',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
