# Generated by Django 4.1.4 on 2023-04-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
