# Generated by Django 4.1.4 on 2023-04-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_game_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
    ]
