# Generated by Django 4.1.4 on 2023-04-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_remove_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
